Enhance Existing `make demo` Script for M4 MacBook Compatibility
kubernetes-sigs/mcs-api pull request #94
Opened 2024-12-27 06:10 UTC by kahirokunn

**Pull Request Title**  
Enhance Existing “make demo” Script for M4 MacBook Compatibility

**Pull Request Description**  
This Pull Request updates the existing “make demo” workflow to fully support M4 MacBook systems, preserving backward compatibility with other environments. Changes include:

- Switching from Python 2 to Python 3 in the edit-meta script.  
- Introducing platform detection to properly handle multi-architecture coredns binaries.  
- Replacing tar-based coredns downloads with a Git clone to account for “make” dependencies.  
- Verifying the new approach locally on an M4 MacBook to confirm all features still work elsewhere.  

These updates ensure that anyone using an M4 MacBook can seamlessly run “make demo” while maintaining compatibility for longstanding setups.

2025-01-06 12:31 UTC, MrFreezeex requested changes
Hi! Welcome and thanks for the contribution! I left a couple of comments, most of them are style/nits except the one about downloading the coredns binary instead of building it which I am concerned about but apart from that this looks great thanks again!

/ok-to-test

2025-01-06 12:31 UTC, MrFreezeex commented on demo/demo.sh
> +script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
```suggestion
cd $(dirname "${BASH_SOURCE[0]}")
script_dir="$(pwd)"
```

2025-01-06 12:31 UTC, MrFreezeex commented on demo/demo.sh
> +kubeconfig2="${KUBECONFIG2:-$(realpath "${script_dir}/../scripts/c2.kubeconfig")}"
This is already an absolute path, realtpath looks redundant here or am I missing something?

2025-01-06 12:31 UTC, MrFreezeex commented on demo/demo.sh
> +# Source the helper scripts with absolute paths.
I don't think we need to re-iterate that we use an absolute path everywhere tbh, if you want you could add that to the first one when script_dir is defined, WDYT?

2025-01-06 12:31 UTC, MrFreezeex commented on demo/demo.sh
> +# Use absolute paths for kubeconfig defaults.
ditto

2025-01-06 12:31 UTC, MrFreezeex commented on scripts/up.sh
> +  chmod +x coredns
The script rebuild the coredns binary because we need to add an out of tree plugin (just a few lines below) so we cannot use the prebuild binary unfortunately

2025-01-06 12:31 UTC, MrFreezeex commented on scripts/up.sh
> +cp ../coredns ./coredns
Ditto, we have to rebuild the coredns binary here

2025-01-06 19:37 UTC, kahirokunn commented on demo/demo.sh
> +kubeconfig2="${KUBECONFIG2:-$(realpath "${script_dir}/../scripts/c2.kubeconfig")}"
Thank you for your feedback. I used `realpath` to prevent paths like `/hoge/fuga/../scripts/c1.kubeconfig` from appearing when using `echo`, aiming for a cleaner output such as `/hoge/scripts/c1.kubeconfig`. However, as you pointed out, it doesn't have any functional impact and is merely a matter of personal preference. I'm not particularly attached to it, so removing `realpath` should be perfectly fine. What are your thoughts on this?

2025-01-06 19:45 UTC, kahirokunn commented on demo/demo.sh
> +# Source the helper scripts with absolute paths.
The proposed commitments have been added. Thank you!

2025-01-06 19:50 UTC, MrFreezeex commented on demo/demo.sh
> +kubeconfig2="${KUBECONFIG2:-$(realpath "${script_dir}/../scripts/c2.kubeconfig")}"
Ah yes ok, thanks for the explanation ,no worries then!

2025-01-06 19:54 UTC, kahirokunn commented on scripts/up.sh
> +  chmod +x coredns
Thank you for your comment.

I reviewed the current `Dockerfile` ([link](https://github.com/coredns/coredns/blob/master/Dockerfile#L14)) and noticed that it primarily utilizes the `docker build` command, which copies the existing CoreDNS binary rather than rebuilding it. This suggests that the binary is not being reconstructed within this specific Docker build process.

Could you please provide more details or point me to the specific script or step where the CoreDNS binary is being rebuilt? Understanding the exact location or method used for the rebuild would greatly help in addressing the integration of the out-of-tree plugin.

I appreciate your guidance and assistance on this matter.

2025-01-06 19:55 UTC, kahirokunn commented on scripts/up.sh
> +cp ../coredns ./coredns
https://github.com/kubernetes-sigs/mcs-api/pull/94#discussion_r1904575177

🙇

2025-01-06 19:57 UTC, MrFreezeex commented on scripts/up.sh
> +  chmod +x coredns
Sure that's when `make` is ran right before the `docker build` command: https://github.com/kubernetes-sigs/mcs-api/blob/fede3192824f8c9d44719a467528f9438ae6007b/scripts/up.sh#L55

2025-01-06 19:59 UTC, kahirokunn commented on scripts/up.sh
> +  chmod +x coredns
I see. Is there a good way to get binaries built that match the container execution environment, rather than binaries that match the host OS environment?
MacOS is hosted on Darwin, but the execution environment is linux.

2025-01-06 20:06 UTC, MrFreezeex commented on scripts/up.sh
> +  chmod +x coredns
Hmm I see :thinking:, maybe something similar to this then: https://github.com/coredns/coredns?tab=readme-ov-file#compilation-with-docker?

2025-01-06 21:25 UTC, kahirokunn commented on scripts/up.sh
> +  chmod +x coredns
Thx! 🙏

2025-01-06 22:29 UTC, kahirokunn commented
/retest-required

2025-01-06 22:31 UTC, kahirokunn commented
I am currently re-testing the functionality. I will provide an update once it is completed.

2025-01-09 04:55 UTC, kahirokunn commented
I've tested this and confirmed it works once this PR is merged.
https://github.com/kubernetes-sigs/mcs-api/pull/97

![CleanShot 2025-01-09 at 13 54 50@2x](https://github.com/user-attachments/assets/8ba17239-9ef8-4b8d-bd34-09ea042a0899)

2025-01-10 07:26 UTC, kahirokunn commented
Testing has been completed successfully. 👍

2025-01-10 07:32 UTC, kahirokunn commented
@MrFreezeex I think I'm falling down with an error in an unrelated area, what do you think I should do?

2025-01-10 09:58 UTC, MrFreezeex commented on scripts/up.sh
> +docker run --rm -i -t \
I think your error in the CI is related to the `-i -t` options here

2025-01-10 12:09 UTC, kahirokunn commented on scripts/up.sh
> +docker run --rm -i -t \
Thx 🙏

2025-01-10 12:32 UTC, kahirokunn commented
It's all been passed!
It's ready to merge. 🙏

2025-01-10 12:56 UTC, MrFreezeex approved these changes
Thanks again!
/lgtm

cc @skitt for approval :pray:

2025-01-29 10:54 UTC, skitt reviewed
Thanks for taking care of this! I have a few suggestions for improvements, if you don’t mind.

2025-01-29 10:54 UTC, skitt commented on demo/demo.sh
> +script_dir="$(pwd)"
Given that there is a `scripts` directory, but this points to `demo`, it would be less confusing to name this `demo_dir`. It would also be useful to have a pointer to the project root, or the `scripts` directory:

```suggestion
demo_dir=$(realpath "$(pwd)")
scripts_dir=$(realpath "$(pwd)/../scripts")
```

(assignments from command substitutions don’t need to be quoted).

2025-01-29 10:54 UTC, skitt commented on demo/demo.sh
> +. "${script_dir}/../scripts/util.sh"
```suggestion
. "${demo_dir}/udemo.sh"
. "${scripts_dir}/util.sh"
```

2025-01-29 10:54 UTC, skitt commented on demo/demo.sh
> +kubeconfig2="${KUBECONFIG2:-$(realpath "${script_dir}/../scripts/c2.kubeconfig")}"
```suggestion
kubeconfig1="${KUBECONFIG1:-${scripts_dir}/c1.kubeconfig}"
kubeconfig2="${KUBECONFIG2:-${scripts_dir}/c2.kubeconfig}"
```

2025-01-29 10:54 UTC, skitt commented on scripts/up.sh
> +        golang:1.23 sh -c 'GOFLAGS="-buildvcs=false" make gen && GOFLAGS="-buildvcs=false" make'
```suggestion
        golang:1.23 make gen coredns GOFLAGS=-buildvcs=false
```

2025-01-29 10:56 UTC, skitt commented
Also, could you rebase your commits to avoid having separate “Apply suggestions from review” commits?

2025-02-01 13:42 UTC, kahirokunn commented
@skitt 
Thank you for the review feedback. I have completed rebasing and squashed the separate review suggestion commits. Please review when you have a chance.

2025-02-18 12:52 UTC, kahirokunn commented
Bump up 👍

2025-02-18 16:16 UTC, dfarrell07 commented
> Also, could you rebase your commits to avoid having separate “Apply suggestions from review” commits?

@kahirokunn I suspect Stephen will still want this clean-up of the commit history. Thanks!

2025-02-19 01:43 UTC, kahirokunn commented
I see, so I've put everything into one commit.
How about now?

2025-02-19 02:19 UTC, dfarrell07 commented
> I see, so I've put everything into one commit. How about now?

I suspect that's fine, thanks. The idea was to avoid the "Apply suggestions from code review" commits. I think multiple commits can be great too if the change is more clearly understood/documented that way. Thanks again!

2025-02-24 09:50 UTC, skitt commented
Thanks @kahirokunn, as Daniel says my concern was with the “Apply suggestions from review” commits. For future reference it would have been fine to keep different commits for the different changes, as long as the suggestions were merged into the corresponding commit.

/approve

2025-02-24 12:11 UTC, MrFreezeex commented
/lgtm

2025-02-24 12:12 UTC, merged